server:
  port: 8883

spring:
  application:
    name: "QuotationService"
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "ecommerce"
      auto-index-creation: "true"
